name: Build V21 code
run-name: ${{ github.actor }} is building
on: [ push ]
jobs:
  Build-code:
    runs-on: [ self-hosted, linux, arm64 ]
    env:
      CARGO_TERM_COLOR: always
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup for ROS2 Humble
        run: vcs import src < src/ros2_rust/ros2_rust_humble.repos
      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env
      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: build
          key: build-${{ runner.os }}-${{ runner.arch }}-${{ runner.name }}
      - name: Cache target outputs
        uses: actions/cache@v4
        with:
          path: src/microcat-rs/target
          key: target-${{ runner.os }}-${{ runner.arch }}-${{ runner.name }}
      - name: build
        run: source /opt/ros/humble/setup.bash && echo ${AMENT_PREFIX_PATH} && colcon build --packages-up-to microcat_rs --merge-install && echo "success" > build.status
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: microcat
          path: install
      - name: lint
        run: cd src/microcat-rs && source /opt/ros/humble/setup.bash && cargo clippy -Fv21_hardware && echo "success" > ../../lint.status && cd ../..

      - name: format
        run: cd src/microcat-rs && source /opt/ros/humble/setup.bash && cargo fmt --check && echo "success" > ../../fmt.status && cd ../..
