name: Build code
run-name: ${{ github.actor }} is building
on: [push]
jobs:
  Build-code:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup for ROS2 Humble
        run: vcs import src < src/ros2_rust/ros2_rust_humble.repos
        
      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: build/
          key: build-cache-${{ github.ref }}
          restore-keys: |
            build-cache-${{ github.ref }}
      - name: Build
        run: source /opt/ros/humble/setup.bash && echo ${AMENT_PREFIX_PATH} && colcon build --packages-up-to microcat_rs --merge-install

      - name: Package Install
        run: tar cvJf microcat.tar.xz install
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: microcat
          path: microcat.tar.xz
      - run: echo "This job's status is ${{ job.status }}."
      - name: Save cache
        if: success()
        uses: actions/cache@v4
        with:
          path: build/
          key: build-cache-${{ github.ref }}
