name: Build V26 code
run-name: ${{ github.actor }} is building
on: [ push ]
jobs:
  Build-code:
    runs-on: [ self-hosted, linux, arm64 ]
    env:
      CARGO_TERM_COLOR: always
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup for ROS2 Humble
        run: vcs import src < src/ros2_rust/ros2_rust_humble.repos
      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env
      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: build
          key: build-${{ runner.os }}-${{ runner.arch }}-${{ runner.name }}
      - name: build
        run: source /opt/ros/humble/setup.bash && echo ${AMENT_PREFIX_PATH} && colcon build --packages-up-to microcat_rs --merge-install && cd src/microcat-rs && cargo ament-build --install-base ../../install -- -Fv26_hardware && cd ../.. && echo "success" > build.status
      - name: Upload install
        uses: actions/upload-artifact@v4
        with:
          name: microcat
          path: install
      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
          name: microcat-rs_v26
          path: src/microcat-rs/target/release/microcat-rs
          compression-level: '0'
      - name: lint
        run: cd src/microcat-rs && source /opt/ros/humble/setup.bash && cargo clippy -Fv26_hardware && echo "success" > ../../lint.status && cd ../..

      - name: format
        run: cd src/microcat-rs && source /opt/ros/humble/setup.bash && cargo fmt --check && echo "success" > ../../fmt.status && cd ../..

      - name: Save status JSON
        if: always()
        run: |
          mkdir -p badges
          echo '{ "schemaVersion": 1, "label": "Build", "message": "'$(cat build.status)'", "color": "'$(cat build.status | grep -q success && echo green || echo red)'" }' > badges/build.json
          echo '{ "schemaVersion": 1, "label": "Lint", "message": "'$(cat lint.status)'", "color": "'$(cat lint.status | grep -q success && echo green || echo red)'" }' > badges/lint.json
          echo '{ "schemaVersion": 1, "label": "Format", "message": "'$(cat fmt.status)'", "color": "'$(cat fmt.status | grep -q success && echo green || echo red)'" }' > badges/fmt.json

      - name: Deploy to gh-pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./badges
          publish_branch: gh-pages
