name: Build code
run-name: ${{ github.actor }} is building
on: [ push ]
jobs:
  Build-code:
    runs-on: [ self-hosted, linux, arm64 ]
    env:
      CARGO_TERM_COLOR: always
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup for ROS2 Humble
        run: vcs import src < src/ros2_rust/ros2_rust_humble.repos
      - name: Cache setup
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./src/microcat-rs -> ../../build/microcat_rs
      - name: Build
        run: source /opt/ros/humble/setup.bash && echo ${AMENT_PREFIX_PATH} && colcon build --packages-up-to microcat_rs --merge-install

      - name: Package Install
        run: tar cvJf microcat.tar.xz install
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: microcat
          path: microcat.tar.xz
