name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check -v

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - name: Install dependencies
        run: sudo apt-get -qq install crossbuild-essential-armhf protobuf-compiler
      - name: Run clippy
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "clippy"
          target: armv7-unknown-linux-gnueabihf
          args: "-- -Dwarnings -Dclippy::pedantic -Dclippy::nursery"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup show
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: sudo apt-get -qq install protobuf-compiler
      - name: Build Code
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: armv7-unknown-linux-gnueabihf
          args: "--locked --release"
      
